apiVersion: apps/v1
kind: deployment
metadata:
  name: pythonimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonimage
template:
  metadata:
    name: pythonimage
  spec:
    containers:
       - name: pythonimage
         image:
         ports:
          - containerport: 8089