apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonimage
  template:
    metadata:
      labels:
        app: pythonimage
    spec:
      containers:
        - name: pythonimage
          image: azurecontainer2026.azurecr.io/pythonimage
          ports:
            - containerPort: 8089
