apiVersion: apps/v1
kind: Deployment
metadata:
    name: pythonimage
spec:
    replicas: 1
    selector:
      matchLabels:
          app: pythonapp
    template:
      metadata:
          name: pythonimage
          labels: 
              app: pythonapp
      spec:
          containers:
              - name: pythonimage
                image: azurecontainer2026.azurecr.io/pythonimage
                ports:
                  - containerPort: 8089
